// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { SchemaTypes as ZodTypes } from './schemas';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'da6de5dc6946f388e508525eca9b03736013ea2543f1a7dcc73b215960c55abe'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly adapter_test: {
    readonly Account: {
      readonly accessToken: CodecTypes['pg/text@1']['output'] | null;
      readonly accessTokenExpiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly accountId: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly idToken: CodecTypes['pg/text@1']['output'] | null;
      readonly password: CodecTypes['pg/text@1']['output'] | null;
      readonly providerId: CodecTypes['pg/text@1']['output'];
      readonly refreshToken: CodecTypes['pg/text@1']['output'] | null;
      readonly refreshTokenExpiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly scope: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
    readonly Person: {
      readonly avatar: CodecTypes['pg/text@1']['output'] | null;
      readonly created: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly displayName: CodecTypes['pg/text@1']['output'];
      readonly emailAddress: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly profileData: ZodTypes['zod/json@1']['schemas']['Profile']['output'];
      readonly updated: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly verified: CodecTypes['pg/bool@1']['output'];
    };
    readonly Session: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly ipAddress: CodecTypes['pg/text@1']['output'] | null;
      readonly token: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly userAgent: CodecTypes['pg/text@1']['output'] | null;
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
    readonly User: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly emailVerified: CodecTypes['pg/bool@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly image: CodecTypes['pg/text@1']['output'] | null;
      readonly lastSeen: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly profile: ZodTypes['zod/json@1']['schemas']['Profile']['output'];
      readonly rich: ZodTypes['zod/json@1']['schemas']['Rich']['output'] | null;
      readonly role: CodecTypes['pg/text@1']['output'] | null;
      readonly score: CodecTypes['pg/int4@1']['output'] | null;
      readonly secret: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Verification: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly identifier: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly value: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly adapter_test: {
    readonly Account: {
      readonly accessToken: CodecTypes['pg/text@1']['input'] | null;
      readonly accessTokenExpiresAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly accountId: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly idToken: CodecTypes['pg/text@1']['input'] | null;
      readonly password: CodecTypes['pg/text@1']['input'] | null;
      readonly providerId: CodecTypes['pg/text@1']['input'];
      readonly refreshToken: CodecTypes['pg/text@1']['input'] | null;
      readonly refreshTokenExpiresAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly scope: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
    readonly Person: {
      readonly avatar: CodecTypes['pg/text@1']['input'] | null;
      readonly created: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly displayName: CodecTypes['pg/text@1']['input'];
      readonly emailAddress: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly profileData: ZodTypes['zod/json@1']['schemas']['Profile']['input'];
      readonly updated: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly verified: CodecTypes['pg/bool@1']['input'];
    };
    readonly Session: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly ipAddress: CodecTypes['pg/text@1']['input'] | null;
      readonly token: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly userAgent: CodecTypes['pg/text@1']['input'] | null;
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
    readonly User: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly emailVerified: CodecTypes['pg/bool@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly image: CodecTypes['pg/text@1']['input'] | null;
      readonly lastSeen: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly profile: ZodTypes['zod/json@1']['schemas']['Profile']['input'];
      readonly rich: ZodTypes['zod/json@1']['schemas']['Rich']['input'] | null;
      readonly role: CodecTypes['pg/text@1']['input'] | null;
      readonly score: CodecTypes['pg/int4@1']['input'] | null;
      readonly secret: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Verification: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly identifier: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly value: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly adapter_test: {
    readonly accounts: {
      readonly accessToken: CodecTypes['pg/text@1']['output'] | null;
      readonly accessTokenExpiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly accountId: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly idToken: CodecTypes['pg/text@1']['output'] | null;
      readonly password: CodecTypes['pg/text@1']['output'] | null;
      readonly providerId: CodecTypes['pg/text@1']['output'];
      readonly refreshToken: CodecTypes['pg/text@1']['output'] | null;
      readonly refreshTokenExpiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly scope: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
    readonly CUSTOM_USERS: {
      readonly avatar: CodecTypes['pg/text@1']['output'] | null;
      readonly created: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly displayName: CodecTypes['pg/text@1']['output'];
      readonly emailAddress: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly profileData: ZodTypes['zod/json@1']['schemas']['Profile']['output'];
      readonly updated: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly verified: CodecTypes['pg/bool@1']['output'];
    };
    readonly login_sessions: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly ipAddress: CodecTypes['pg/text@1']['output'] | null;
      readonly token: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly userAgent: CodecTypes['pg/text@1']['output'] | null;
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
    readonly People: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly emailVerified: CodecTypes['pg/bool@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly image: CodecTypes['pg/text@1']['output'] | null;
      readonly lastSeen: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly profile: ZodTypes['zod/json@1']['schemas']['Profile']['output'];
      readonly rich: ZodTypes['zod/json@1']['schemas']['Rich']['output'] | null;
      readonly role: CodecTypes['pg/text@1']['output'] | null;
      readonly score: CodecTypes['pg/int4@1']['output'] | null;
      readonly secret: CodecTypes['pg/text@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly verifications: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly identifier: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly value: CodecTypes['pg/text@1']['output'];
    };
  };
  readonly public: {};
};
export type StorageColumnInputTypes = {
  readonly adapter_test: {
    readonly accounts: {
      readonly accessToken: CodecTypes['pg/text@1']['input'] | null;
      readonly accessTokenExpiresAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly accountId: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly idToken: CodecTypes['pg/text@1']['input'] | null;
      readonly password: CodecTypes['pg/text@1']['input'] | null;
      readonly providerId: CodecTypes['pg/text@1']['input'];
      readonly refreshToken: CodecTypes['pg/text@1']['input'] | null;
      readonly refreshTokenExpiresAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly scope: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
    readonly CUSTOM_USERS: {
      readonly avatar: CodecTypes['pg/text@1']['input'] | null;
      readonly created: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly displayName: CodecTypes['pg/text@1']['input'];
      readonly emailAddress: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly profileData: ZodTypes['zod/json@1']['schemas']['Profile']['input'];
      readonly updated: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly verified: CodecTypes['pg/bool@1']['input'];
    };
    readonly login_sessions: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly ipAddress: CodecTypes['pg/text@1']['input'] | null;
      readonly token: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly userAgent: CodecTypes['pg/text@1']['input'] | null;
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
    readonly People: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly emailVerified: CodecTypes['pg/bool@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly image: CodecTypes['pg/text@1']['input'] | null;
      readonly lastSeen: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly profile: ZodTypes['zod/json@1']['schemas']['Profile']['input'];
      readonly rich: ZodTypes['zod/json@1']['schemas']['Rich']['input'] | null;
      readonly role: CodecTypes['pg/text@1']['input'] | null;
      readonly score: CodecTypes['pg/int4@1']['input'] | null;
      readonly secret: CodecTypes['pg/text@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly verifications: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly expiresAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly identifier: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly value: CodecTypes['pg/text@1']['input'];
    };
  };
  readonly public: {};
};

export namespace Models {
  export type adapter_test_Account = {
    accessToken: CodecTypes['pg/text@1']['output'] | null;
    accessTokenExpiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    accountId: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    idToken: CodecTypes['pg/text@1']['output'] | null;
    password: CodecTypes['pg/text@1']['output'] | null;
    providerId: CodecTypes['pg/text@1']['output'];
    refreshToken: CodecTypes['pg/text@1']['output'] | null;
    refreshTokenExpiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    scope: CodecTypes['pg/text@1']['output'] | null;
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    userId: CodecTypes['pg/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type adapter_test_Person = {
    avatar: CodecTypes['pg/text@1']['output'] | null;
    created: CodecTypes['pg/timestamptz-temporal@1']['output'];
    displayName: CodecTypes['pg/text@1']['output'];
    emailAddress: CodecTypes['pg/text@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    profileData: ZodTypes['zod/json@1']['schemas']['Profile']['output'];
    updated: CodecTypes['pg/timestamptz-temporal@1']['output'];
    verified: CodecTypes['pg/bool@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type adapter_test_Session = {
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    expiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    ipAddress: CodecTypes['pg/text@1']['output'] | null;
    token: CodecTypes['pg/text@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    userAgent: CodecTypes['pg/text@1']['output'] | null;
    userId: CodecTypes['pg/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type adapter_test_User = {
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    emailVerified: CodecTypes['pg/bool@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    image: CodecTypes['pg/text@1']['output'] | null;
    lastSeen: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    name: CodecTypes['pg/text@1']['output'];
    profile: ZodTypes['zod/json@1']['schemas']['Profile']['output'];
    rich: ZodTypes['zod/json@1']['schemas']['Rich']['output'] | null;
    role: CodecTypes['pg/text@1']['output'] | null;
    score: CodecTypes['pg/int4@1']['output'] | null;
    secret: CodecTypes['pg/text@1']['output'] | null;
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type adapter_test_Verification = {
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    expiresAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    id: CodecTypes['pg/text@1']['output'];
    identifier: CodecTypes['pg/text@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    value: CodecTypes['pg/text@1']['output'];
    readonly [RelationKeys]?: never;
  };
}

export declare const models: {
  adapter_test: {
    Account: Models.adapter_test_Account;
    Person: Models.adapter_test_Person;
    Session: Models.adapter_test_Session;
    User: Models.adapter_test_User;
    Verification: Models.adapter_test_Verification;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly adapter_test: {
        readonly id: 'adapter_test';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly accounts: {
              columns: {
                readonly accessToken: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly accessTokenExpiresAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly accountId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly idToken: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly password: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly providerId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly refreshToken: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly refreshTokenExpiresAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly scope: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly userId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly CUSTOM_USERS: {
              columns: {
                readonly avatar: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly created: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly displayName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly emailAddress: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly profileData: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'zod/json@1';
                  readonly nullable: false;
                  readonly typeParams: {
                    readonly export: 'SchemaTypes';
                    readonly key: 'Profile';
                    readonly module: './schemas';
                  };
                };
                readonly updated: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly verified: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['emailAddress'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly login_sessions: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly expiresAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly ipAddress: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly token: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly userAgent: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly userId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['token'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly People: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly emailVerified: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly image: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly lastSeen: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly profile: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'zod/json@1';
                  readonly nullable: false;
                  readonly typeParams: {
                    readonly export: 'SchemaTypes';
                    readonly key: 'Profile';
                    readonly module: './schemas';
                  };
                };
                readonly rich: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'zod/json@1';
                  readonly nullable: true;
                  readonly typeParams: {
                    readonly export: 'SchemaTypes';
                    readonly key: 'Rich';
                    readonly module: './schemas';
                  };
                };
                readonly role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly score: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly secret: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly verifications: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly expiresAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly identifier: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly value: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: { readonly table: {} };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly CUSTOM_USERS: {
      readonly namespace: 'adapter_test' & NamespaceId;
      readonly model: 'Person';
    };
    readonly People: { readonly namespace: 'adapter_test' & NamespaceId; readonly model: 'User' };
    readonly accounts: {
      readonly namespace: 'adapter_test' & NamespaceId;
      readonly model: 'Account';
    };
    readonly login_sessions: {
      readonly namespace: 'adapter_test' & NamespaceId;
      readonly model: 'Session';
    };
    readonly verifications: {
      readonly namespace: 'adapter_test' & NamespaceId;
      readonly model: 'Verification';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly adapter_test: {
        readonly models: {
          readonly Account: {
            readonly fields: {
              readonly accessToken: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly accessTokenExpiresAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly accountId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly idToken: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly password: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly providerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly refreshToken: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly refreshTokenExpiresAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly scope: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'accounts';
              readonly namespaceId: 'adapter_test';
              readonly fields: {
                readonly accessToken: { readonly column: 'accessToken' };
                readonly accessTokenExpiresAt: { readonly column: 'accessTokenExpiresAt' };
                readonly accountId: { readonly column: 'accountId' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly id: { readonly column: 'id' };
                readonly idToken: { readonly column: 'idToken' };
                readonly password: { readonly column: 'password' };
                readonly providerId: { readonly column: 'providerId' };
                readonly refreshToken: { readonly column: 'refreshToken' };
                readonly refreshTokenExpiresAt: { readonly column: 'refreshTokenExpiresAt' };
                readonly scope: { readonly column: 'scope' };
                readonly updatedAt: { readonly column: 'updatedAt' };
                readonly userId: { readonly column: 'userId' };
              };
            };
          };
          readonly Person: {
            readonly fields: {
              readonly avatar: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly created: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly displayName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly emailAddress: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly profileData: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'zod/json@1';
                  readonly typeParams: {
                    readonly export: 'SchemaTypes';
                    readonly key: 'Profile';
                    readonly module: './schemas';
                  };
                };
              };
              readonly updated: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly verified: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'CUSTOM_USERS';
              readonly namespaceId: 'adapter_test';
              readonly fields: {
                readonly avatar: { readonly column: 'avatar' };
                readonly created: { readonly column: 'created' };
                readonly displayName: { readonly column: 'displayName' };
                readonly emailAddress: { readonly column: 'emailAddress' };
                readonly id: { readonly column: 'id' };
                readonly profileData: { readonly column: 'profileData' };
                readonly updated: { readonly column: 'updated' };
                readonly verified: { readonly column: 'verified' };
              };
            };
          };
          readonly Session: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly expiresAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly ipAddress: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly token: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly userAgent: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'login_sessions';
              readonly namespaceId: 'adapter_test';
              readonly fields: {
                readonly createdAt: { readonly column: 'createdAt' };
                readonly expiresAt: { readonly column: 'expiresAt' };
                readonly id: { readonly column: 'id' };
                readonly ipAddress: { readonly column: 'ipAddress' };
                readonly token: { readonly column: 'token' };
                readonly updatedAt: { readonly column: 'updatedAt' };
                readonly userAgent: { readonly column: 'userAgent' };
                readonly userId: { readonly column: 'userId' };
              };
            };
          };
          readonly User: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly emailVerified: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly image: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lastSeen: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly profile: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'zod/json@1';
                  readonly typeParams: {
                    readonly export: 'SchemaTypes';
                    readonly key: 'Profile';
                    readonly module: './schemas';
                  };
                };
              };
              readonly rich: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'zod/json@1';
                  readonly typeParams: {
                    readonly export: 'SchemaTypes';
                    readonly key: 'Rich';
                    readonly module: './schemas';
                  };
                };
              };
              readonly role: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly score: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly secret: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'People';
              readonly namespaceId: 'adapter_test';
              readonly fields: {
                readonly createdAt: { readonly column: 'createdAt' };
                readonly email: { readonly column: 'email' };
                readonly emailVerified: { readonly column: 'emailVerified' };
                readonly id: { readonly column: 'id' };
                readonly image: { readonly column: 'image' };
                readonly lastSeen: { readonly column: 'lastSeen' };
                readonly name: { readonly column: 'name' };
                readonly profile: { readonly column: 'profile' };
                readonly rich: { readonly column: 'rich' };
                readonly role: { readonly column: 'role' };
                readonly score: { readonly column: 'score' };
                readonly secret: { readonly column: 'secret' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Verification: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly expiresAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly identifier: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly value: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'verifications';
              readonly namespaceId: 'adapter_test';
              readonly fields: {
                readonly createdAt: { readonly column: 'createdAt' };
                readonly expiresAt: { readonly column: 'expiresAt' };
                readonly id: { readonly column: 'id' };
                readonly identifier: { readonly column: 'identifier' };
                readonly updatedAt: { readonly column: 'updatedAt' };
                readonly value: { readonly column: 'value' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {
    readonly zod: {
      readonly familyId: 'sql';
      readonly id: 'zod';
      readonly kind: 'extension';
      readonly targetId: 'postgres';
      readonly types: {
        readonly codecTypes: {
          readonly import: {
            readonly alias: 'ZodTypes';
            readonly named: 'SchemaTypes';
            readonly package: './schemas';
          };
        };
        readonly storage: readonly [
          {
            readonly familyId: 'sql';
            readonly nativeType: 'jsonb';
            readonly targetId: 'postgres';
            readonly typeId: 'zod/json@1';
          },
        ];
      };
      readonly version: '0.1.0';
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
